# Generated by Django 4.1.2 on 2022-10-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myajax", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="sangdata", options={"managed": False},),
    ]
